#:schema https://hexdoc.hexxy.media/schema/core/Properties.json

modid = "hexal"
book = "hexcasting:thehexbook"

resource_dirs = [  # top takes priority
    "resources",
    "{$_common.src}/main/resources",
    "{$_common.src}/generated/resources",
    "{$_fabric.src}/main/resources",
    "{$_fabric.src}/generated/resources",
    "{$_forge.src}/main/resources",
    "{$_forge.src}/generated/resources",
    { modid="moreiotas" },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexal/_export/generated"

[template]
icon = "../art/logo.png"
include = [
    "hexal",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hexal"
author = "FallingColors"
show_landing_text = false

[textures]
strict = false
missing = [
    "minecraft:chest",
]

[extra.hexcasting]
# regex for parsing pattern registry files
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex."!Raw" = '''(?mx)
^
[^\n/]*
make\(
    \s*
    "(?P<name>[a-zA-Z0-9_\/]+)",
    \s*
    HexPattern\.fromAngles\(
        \s*
        "(?P<signature>[aqweds]+)",
        \s*
        HexDir.(?P<startdir>\w+),?
        \s*
    \)
'''

[[extra.hexcasting.pattern_stubs]]
path = "{$_common.package}/common/lib/hex/HexalActions.kt"
regex = "{^_pattern_regex}"

[[extra.hexcasting.pattern_stubs]]
path = "{$_fabric.package}/FabricHexalInitializer.kt"
regex = "{^_pattern_regex}"

# platforms

[_common]
src = "../Common/src"
package = "{src}/main/java/ram/talia/hexal"

[_fabric]
src = "../Fabric/src"
package = "{src}/main/java/ram/talia/hexal/fabric"

[_forge]
src = "../Forge/src"
package = "{src}/main/java/ram/talia/hexal/forge"
